stages:
  - test
  - build
  - deploy

sonarqube-check:
  stage: test
  image: sonarsource/sonar-scanner-cli:latest
  script:
    - sonar-scanner -Dsonar.projectKey=$SONAR_PROJECT_KEY -Dsonar.sources=. -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.token=$SONAR_TOKEN
  only:
    - main

docker-build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - cd spring-boot-app
    - docker build -t my-app:latest .
    - docker save my-app:latest > ../my-app.tar
  artifacts:
    paths:
      - my-app.tar

docker-push:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - docker load < my-app.tar
    - docker tag my-app:latest $DOCKER_USER/python_minikubw:latest
    - docker push $DOCKER_USER/python_minikubw:latest